"""Generate one config file per experiment of the paper.

The configs are derived from the original configs, with the hyperparameters of
Section 1 of the supplementary material:

- LSTR  (long-short-term-transformer/configs/Struggle/LSTR/lstr_anticipation_4sec.yaml):
  cross-entropy loss, batch size 16, 20 epochs, base lr 1e-6, dropout 0.2
  (0.4 for Tying Knots); 50 epochs and base lr 1e-7 when trained on all activities.
- CMeRT (CMeRT/configs/Struggle/cmert_long512_work8_kinetics_1x.yaml):
  batch size 32, 15 epochs, base lr 5e-6, dropout 0.3, for all experiments.

Only the split file, the subsets and the settings above are changed.

Usage (from the root of the repository):
    python tools/generate_struggle_configs.py
"""
import os
import re

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
# paths are relative to the codebase directory (CMeRT/ or long-short-term-transformer/)
DATA_ROOT = '../data/EvoStruggle'
COMBINED_SPLIT = '../splits/combined_split.json'

# (directory name in EvoStruggle, short name used in file names, task ids)
ACTIVITIES = [
    ('Tying_Knots', 'tyingknots', [1, 2, 3, 4, 5]),
    ('Origami', 'origami', [1, 2, 3, 4]),
    ('Tangram', 'tangram', [1, 2, 3, 4]),
    ('Shuffle_Cards', 'shufflecards', [1, 2, 3, 4, 5]),
]
ALL_ATTEMPTS = ['train_attempt{:02d}'.format(i) for i in range(1, 6)]

LSTR_BASE = 'long-short-term-transformer/configs/Struggle/LSTR/lstr_anticipation_4sec.yaml'
CMERT_BASE = 'CMeRT/configs/Struggle/cmert_long512_work8_kinetics_1x.yaml'
HEADER = '# Generated by tools/generate_struggle_configs.py -- do not edit by hand.\n'


def sepattempt(act):
    return f'{DATA_ROOT}/splits/separate_attempts/{act}/{act}_sepattempt.json'


def set_field(text, key, value):
    """Replace the value of the (unique) `key:` line, keeping its indentation."""
    pattern = re.compile(r'^(\s*)' + re.escape(key) + r':.*$', re.MULTILINE)
    assert len(pattern.findall(text)) == 1, key
    return pattern.sub(lambda m: f'{m.group(1)}{key}: {value}', text)


def make_config(base, split, train, test, comment, **fields):
    text = base
    text = set_field(text, 'DATA_ROOT', f"'{DATA_ROOT}'")
    text = set_field(text, 'DATA_SPLIT_PATH', f"'{split}'")
    text = set_field(text, 'TRAIN_SEUBSET', str(train))
    text = set_field(text, 'TEST_SUBSET', str(test))
    text = set_field(text, 'ENABLE_WANDB', 'False')
    for key, value in fields.items():
        text = set_field(text, key, value)
    if 'CHECKPOINT:' in text:
        text = set_field(text, 'CHECKPOINT', "''")
    return HEADER + f'# {comment}\n' + text


def lstr_configs(base):
    """LSTR: Table 1 (individual and combined training; detection and 2 s anticipation) and Fig. 2 (left)."""
    for act, short, _ in ACTIVITIES:
        dropout = '0.4' if act == 'Tying_Knots' else '0.2'
        # online detection is the special case of anticipation with delta = 0 (Sec. 3.2):
        # LSTR is trained without anticipation tokens for the detection results (Table 1, Det.)
        yield 'within_activity', f'lstr_{short}_det', make_config(
            base, sepattempt(act), ALL_ATTEMPTS, ['validation'], f'Table 1 (individual training), detection: {act}',
            DROPOUT=dropout, ANTICIPATION_SECONDS='0')
        for sec in (2, 4, 6, 8):
            setting = 'within_activity' if sec == 2 else 'anticipation_length'
            comment = (f'Table 1 (individual training): {act}' if sec == 2
                       else f'Fig. 2 (left), anticipation length {sec} s: {act}')
            yield setting, f'lstr_{short}_ant{sec}s', make_config(
                base, sepattempt(act), ALL_ATTEMPTS, ['validation'], comment,
                DROPOUT=dropout, ANTICIPATION_SECONDS=str(sec))
    yield 'combined', 'lstr_combined_det', make_config(
        base, COMBINED_SPLIT, ['train'], ['validation'], 'Table 1 (combined training), detection: all four activities',
        ANTICIPATION_SECONDS='0', NUM_EPOCHS='50', BASE_LR='1e-7')
    yield 'combined', 'lstr_combined_ant2s', make_config(
        base, COMBINED_SPLIT, ['train'], ['validation'], 'Table 1 (combined training): all four activities',
        ANTICIPATION_SECONDS='2', NUM_EPOCHS='50', BASE_LR='1e-7')


def cmert_configs(base):
    """CMeRT: Table 1, Table 2, Table 3 and Figs. 6-8."""
    for act, short, tasks in ACTIVITIES:
        yield 'within_activity', f'cmert_{short}', make_config(
            base, sepattempt(act), ALL_ATTEMPTS, ['validation'], f'Table 1 (individual training): {act}')
        js = f'{DATA_ROOT}/splits/crossdomain_generalization/{act}/{act}_crossdomain_testonvalonly.json'
        yield 'activity_generalization', f'cmert_activitygen_{short}', make_config(
            base, js, ['train'], ['test'],
            f'Table 2: train on the other three activities, test on the validation set of {act}')
        for t in tasks:
            js = f'{DATA_ROOT}/splits/indomain_generalization/{act}/{act}_subactivity{t:02d}_data.json'
            yield 'task_generalization', f'cmert_taskgen_{short}_task{t:02d}', make_config(
                base, js, ['train'], ['test'], f'Table 3: {act}, held-out task {t:02d}')
        for i, attempt in enumerate(ALL_ATTEMPTS, 1):
            yield 'separate_attempts', f'cmert_sepattempt_{short}_attempt{i:02d}', make_config(
                base, sepattempt(act), [attempt], ['validation'],
                f'Figs. 6-8: {act}, trained on attempt {i:02d} only')
    yield 'combined', 'cmert_combined', make_config(
        base, COMBINED_SPLIT, ['train'], ['validation'], 'Table 1 (combined training): all four activities')


def main():
    with open(os.path.join(REPO_ROOT, LSTR_BASE)) as f:
        lstr_base = f.read()
    with open(os.path.join(REPO_ROOT, CMERT_BASE)) as f:
        cmert_base = set_field(f.read(), 'NUM_EPOCHS', '15')

    n = 0
    for codebase, sub, configs in [
            ('long-short-term-transformer', 'LSTR', lstr_configs(lstr_base)),
            ('CMeRT', '', cmert_configs(cmert_base))]:
        for setting, name, text in configs:
            out_dir = os.path.join(REPO_ROOT, codebase, 'configs', 'Struggle', sub, 'paper', setting)
            os.makedirs(out_dir, exist_ok=True)
            with open(os.path.join(out_dir, name + '.yaml'), 'w') as f:
                f.write(text)
            n += 1
    print(f'Generated {n} config files.')


if __name__ == '__main__':
    main()
